### ISSUE TITLE
Repetition in workflows

### ISSUE THREAD

**Issue by jembrown** [TreeScaper/CloudforestDocker#2]
@reid-wagner Is it possible to set up something like a for loop in Galaxy workflows? I was working on an example workflow for outlier detection, but I need to do IQTree analyses for hundreds of genes and then combine their output to analyze them in TreeScaper. This sort of repetition will be necessary for most phylogenomic analyses.

**Comment by reid-wagner** [comment]
Hi @jembrown,

It looks like [Galaxy collections](https://galaxyproject.org/tutorials/collections/) might be a good solution for this. You can create a collection of multiple datasets and run a tool like IQTree on the collection, producing further collections containing the outputs.

So running IQTree on the collection sequence files will output a collection of bootstrap trees. I'm not sure how simple it is to combine nhx files - is there an existing tool you use for this? There is a `Statistics->Concatenate datasets` tool that I tested, which does just concatenate datasets in a collection to output a single file.

Collections can be used in workflows (`Inputs -> Input dataset collection`), so a single workflow could represent an operation on hundreds of files.

**Comment by btoup15** [comment]
Hey Reid, is the concatenate datasets tool in the current build of cloudforest? All I have under that dropdown are summary statistics and count

**Comment by jembrown** [comment]
@reid-wagner Thanks! I was able to set up a collection of input datasets and successfully run them all through IQTree.

I think the output trees are stored individually in plain text files, so a simple concatenation should work well to combine them. +1 to @btoup15's question, though.

**Comment by reid-wagner** [comment]
Ah, it's installed on the beta site but not as a default in CloudForest. I'll look into the best way to include it here. In the meantime you should be able to install it on your local instance by logging in with the default username and pass `admin`:`admin`.

Navigate to Admin -> Tool Management -> Install or Uninstall, then search for and install `text_processing` (you can leave the `Target Section` field blank.

**Comment by jembrown** [comment]
@reid-wagner Thanks, that worked and I was able to install the tool in my local instance. However, when I try to select a collection to concatenate, it's only allowing me to select my original collection of datasets and not any of the IQTree output collections. I think this may be because a few of the IQTree runs failed due to problems with particular datasets, although most ran fine. Is it possible to edit out those problematic outputs from the resulting collections or do I need to remove the individual datasets from the original collection and start over?

**Comment by reid-wagner** [comment]
I wasn't able to find a way to just manually delete items out of a collection, which is surprising. But, I did add a set of tools called "collection operations" to the default CloudForest image, one of which can filter out failed datasets.

I'm working on getting access to Docker Hub organization so I can push the latest image, in the meantime I've updated `run.sh` so it's a little easier to build & deploy your own image from master with the following command:

`sh run.sh <tag> <container_name> [volume]`

where `tag` and `container_name` can really be whatever you want, it just names those two fields for your image and container. The `volume` argument is optional, but you can supply the name of the volume you created for data persistence.

**Comment by btoup15** [comment]
To follow up on @jembrown 's comment, I was able to select my output dataset collection and fully concatenate all of the files with the tool Reid suggested. To do so I went to concatenate datasets and clicked the "dataset collections" option near the input field, and that allowed me to select the bootstrap trees collection and fully concatenate all of the contents. Not sure if this is something Jeremy tried, but hope this helps!

**Comment by reid-wagner** [comment]
@jembrown I wrote a small tool to concatenate datasets from a collection, under `CloudForest Utilities -> Concatenate`.

It's included in the image with the `latest` tag. Let me know if you encounter any issues.

**Comment by jembrown** [comment]
Thanks, @reid-wagner. The combination of collections and the concatenation tool seem to be working well for repetitious analyses. There do seem to be some inherent limits on the number of independent datasets that can be analyzed as part of a single collection, but this seems to be at the level of Galaxy overall and not CloudForest.
