### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by btoup15** [TreeScaper/CloudforestDocker#4]
Currently when I try to run any TreeScaper analysis, upon executing the job it returns the error `/export/galaxy-central/database/job_working_directory/000/508/tool_script.sh: line 9: /export/galaxy-central/tools/treescaper/CLVTreeScaper: Permission denied`. 
This has occurred for me using the concatenated dataset from the other open issue, as well as a normal dataset uploaded directly from my computer. Are either of you able to reproduce this? @jembrown @reid-wagner

**Comment by reid-wagner** [comment]
This appears to be an issue when using volumes. I pushed a fix about about an hour and a half ago here: https://github.com/TreeScaper/CloudforestDocker/commit/e4459db0c334bedbedf2511560de4de0a946e60b.

Have you either rebuilt the image or pulled the latest from Docker Hub since that commit?

**Comment by btoup15** [comment]
I haven't, I'll pull the newer image and check it out. Thanks Reid!
